### ISSUE TITLE
sha1 parameter not present in LTS jenkins 1.651.2 + ghprb 1.32.2, parametrized jobs

### ISSUE THREAD

**Issue by kad** [jenkinsci/ghprb-plugin#355] opened 2016-05-30 09:49 UTC
After upgrading to LTS 1.651.2 and latest stable version of ghprb plugin 1.32.2, I observe builds that have sha1 parameter undefined. Jobs were configured with DSL:

```groovy
freeStyleJob('xxxx_pull-requests') {
  parameters {
    stringParam('sha1', null, null)
  }
    githubPullRequest {
      cron("${scm_poll_short}")
      useGitHubHooks()
    }
  }
...
}
```
Build was triggered, ghprb* variables were populated to environment, however, sha1 was not present. it can be seen here:  https://ostroproject.org/jenkins/job/dsl-meta-ostro_pull-requests/1514/

After I removed stringParameter() from DSL, jobs started to be populating sha1 variable properly: https://ostroproject.org/jenkins/job/dsl-meta-ostro_pull-requests/1515/ , but that means it's impossible to start those jobs manually anymore.

**Comment by mvk** [comment] 2016-05-30 15:08
This happens to me without DSL on the old jenkins (1.65*), did not validate this in DSL with jenkins 2.7, but my guess is it would reproduce.

**Comment by petacz** [comment] 2016-05-30 19:54
Same problem here.
I am not using DSL.

**Comment by dmaicher** [comment] 2016-05-31 13:51
I might have the same issue today after upgrading to Jenkins 2.7 and plugin version 1.32.2. The environment variable `${ghprbSourceBranch}` is suddenly empty... :(

Could be connected?

**Comment by stgraber** [comment] 2016-05-31 16:56
I'm seeing the same using Jenkins 2.7 and plugin 1.32.2. ${sha1} is now using the default value rather than the correct value for the pull request.

**Comment by stgraber** [comment] 2016-05-31 16:57
When dumping the environment I see:
```
JENKINS_HOME=/var/lib/jenkins
GIT_PREVIOUS_SUCCESSFUL_COMMIT=0a8fca094e61abd5332bcf43f321ede0bdb5fda7
NODE_LABELS=amd64 i386 lxc-priv stgraber-buildd01
HUDSON_URL=https://jenkins.linuxcontainers.org/
GIT_COMMIT=b4b75e16db84f5bd3f4171046ef062e0926d6a3a
OLDPWD=/home/jenkins/workspace/lxc-github-pull-test/arch/amd64/compiler/gcc/restrict/lxc-priv
BUILD_URL=https://jenkins.linuxcontainers.org/job/lxc-github-pull-test/arch=amd64,compiler=gcc,restrict=lxc-priv/310/
JENKINS_SERVER_COOKIE=abcdef
HUDSON_COOKIE=abcdef
WORKSPACE=/home/jenkins/workspace/lxc-github-pull-test/arch/amd64/compiler/gcc/restrict/lxc-priv
restrict=lxc-priv
UPSTART_JOB=jenkins-slave
NODE_NAME=stgraber-buildd01
arch=amd64
EXECUTOR_NUMBER=5
GIT_BRANCH=origin/master
TERM=linux
BUILD_DISPLAY_NAME=#310
JOB_BASE_NAME=arch=amd64,compiler=gcc,restrict=lxc-priv
HUDSON_HOME=/var/lib/jenkins
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
sha1=master
BUILD_ID=310
BUILD_TAG=jenkins-lxc-github-pull-test-arch=amd64,compiler=gcc,restrict=lxc-priv-310
JENKINS_URL=https://jenkins.linuxcontainers.org/
JOB_URL=https://jenkins.linuxcontainers.org/job/lxc-github-pull-test/arch=amd64,compiler=gcc,restrict=lxc-priv/
GIT_URL=https://github.com/lxc/lxc
compiler=gcc
BUILD_NUMBER=310
HUDSON_SERVER_COOKIE=abcdef
JOB_NAME=lxc-github-pull-test/arch=amd64,compiler=gcc,restrict=lxc-priv
PWD=/lxc
```

**Comment by mvk** [comment] 2016-05-31 18:43
I have looked at the code of ghprb-plugin, and the commit for last tag is moving something related to initialization of the environment of the build. I smell a dead mouse there: the implementation code moved to another file, but reference to that call has been removed.
Just run: `git diff --stat ghprb-1.32.1..ghprb-1.32.2`
you can see 2 code files have been change.
one is removals of code, and the other - refactored addition.
One of the removals in `src/main/java/org/jenkinsci/plugins/ghprb/GhprbAdditionalParameterEnvironmentContributor.java`:
```
public class GhprbAdditionalParameterEnvironmentContributor extends EnvironmentContributor {
@@ -27,7 +22,6 @@ public class GhprbAdditionalParameterEnvironmentContributor extends EnvironmentC
         if (cause == null) {
             return;
         }
-        run.addAction(getDefaultParameters(run));
 
         final String commitSha = cause.isMerged() ? "origin/pr/" + cause.getPullID() + "/merge" : cause.getCommit();
         putEnvVar(envs, "sha1", commitSha);
@@ -78,18 +72,6 @@ public class GhprbAdditionalParameterEnvironmentContributor extends EnvironmentC
```
I have no idea how the other file helps, but it seems the code only implement the initialization, without it actually having been called.
So the fix is supposedly to change how the default parameters for the actions are initialized.

Am I wrong?

**Comment by dmaicher** [comment] 2016-05-31 18:56
I actually have the same issue with the empty environment variable with plugin version 1.31.4

**Comment by mvk** [comment] 2016-06-01 06:03
hmmm..

**Comment by dmaicher** [comment] 2016-06-01 06:40
I just checked and maybe its related to my Jenkins update to version 2.7?

With ghprb versions 1.29 and 1.30 I have the same issue :cry:

**Comment by jmslagle** [comment] 2016-06-02 15:36
We're having the issue too, which is pretty much making the plugin unusable - without the sha1 it ends up building ALL of the PR's every time.  Ug.

**Comment by martenson** [comment] 2016-06-03 21:50
we have the same problem; downgrading to 1.32.1 does not help;

**Comment by nickmshelley** [comment] 2016-06-06 18:31
This is happening to us as well. We got it to run the correct PR by removing the sha1 parameter from our Jenkins job, but now all pending builds are combined into a single build and only the first one is run, so we get a job that looks like this (which will only run and comment on 2176):

```
GitHub pull request #2176 of commit db84c1fa12b075266382bda60be22eb6565a69ae, no merge conflicts.

GitHub pull request #2175 of commit 74ba2a1b47ccf2cbc2fb34d6226f2a72b93bee65, no merge conflicts.

GitHub pull request #2177 of commit c5137f73f140c424fdc739ad159c8afbce1ade95, no merge conflicts.

GitHub pull request #2174 of commit 77391fda7f78ffdb3c84f1471fa29e86c5c5026f, no merge conflicts.

GitHub pull request #2177 of commit 5a5e3fd09c397545b175a3e6b730ee86028ed8df, has merge conflicts.

GitHub pull request #2177 of commit 98bc00e3561e619f296a489a5d0d512fb10cb5d6, no merge conflicts.
```

**Comment by ermshiperete** [comment] 2016-06-06 19:14
When I remove the build parameter (parameterized build) thing start to work again. Looks like it doesn't like it when a build parameter has the same name as a variable that ghprb-plugin defines...

**Comment by martenson** [comment] 2016-06-06 19:47
@ermshiperete correct, that is the workaround described in the first post, it prevents you from triggering the builds manually though

**Comment by nickmshelley** [comment] 2016-06-06 20:07
It also doesn't allow more than one build to be in the queue (not running) at a time, as I mentioned in my earlier comment.

**Comment by stephanheilner** [comment] 2016-06-06 21:56
Removing the parameterized build setting doesn't make a difference for me. I'm seeing what @nickmshelley is seeing, where multiple PRs are being added to my queued up jobs. Before, each PR would be its own job in the queue.

**Comment by kad** [comment] 2016-06-07 09:03
ghprb-1.32.3 seems to have some fixes for parameters, but there is no changelog and I haven't tried this version yet.

**Comment by luis-silva** [comment] 2016-06-07 17:04
The commit for this new version (1.32.3) only seems to change code related to params so I decided to give it a go. It seems to have fixed this problem but I'm currently testing it.

**Comment by benpatterson** [comment] 2016-09-30 09:32
I'm helping out with this repo and looking at older issues. This looks like a duplicate of #352

**Closed by benpatterson** 2016-09-30 09:32 UTC

**Comment by dalejoel** [comment] 2016-11-04 16:57
I am running 1.33.1 and had to add every missing parameter (which was a lot) to my job. That got the warning messages to go away and it seems to be building the correct sha1 and only creating one job per pull request. So is there still a problem? 

Any proposed solution for all the parameters though? I would love to not have to add 23 parameters to all of my jobs. I have a lot of them.
