### ISSUE TITLE
Retest PR cause Github API call failed with 404

### ISSUE THREAD

**Issue by richard1122** [jenkinsci/ghprb-plugin#441] opened 2016-11-28 12:09 UTC
After comments on a Github PR "retest this please". Jenkins could not rebuild, and the following exception is logged in Jenkins log page.

It might be `https://api.github.com/repos/<UserName>/<RepoName>/pulls/4/commits` .

* Plugin version: 1.33.2

```
A thread (Thread-9/80) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.Error: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:433)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:400)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:365)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:214)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:346)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:618)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$1.run(GhprbRootAction.java:233)
Caused by: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:592)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:429)
	... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/<UserName>/<RepoName>/issues/4/commits
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:524)
	at org.kohsuke.github.Requester.access$200(Requester.java:68)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:424)
	... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/<UserName>/<RepoName>/issues/4/commits
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:514)
	... 10 more
```

**Comment by benpatterson** [comment] 2016-11-28 13:02
Richard

* What version of the plugin are you using?
* Did you check your Github access for the user/token you are using for the
plugin?  (Check the global configuration and the job)
* How about the connectivity between your Jenkins instance and Github?

In a vacuum this looks like either a permissions issue or a network issue.

**Comment by richard1122** [comment] 2016-11-28 13:50
Hi,

* Plugin version: 1.33.2
* I've tested the token with `curl`, the `https://api.github.com/repos/<UserName>/<RepoName>/issues/4/commits` returns 404, and `https://api.github.com/repos/<UserName>/<RepoName>/pulls/4/commits` returns fine. (change issues to pulls).
* I've also tested in jenkins configuration page with the same repo:
![image](https://cloud.githubusercontent.com/assets/2534277/20670606/93640f74-b5b4-11e6-93d1-dc635e9d844e.png)
![image](https://cloud.githubusercontent.com/assets/2534277/20670608/995a1842-b5b4-11e6-90cf-c66d8150b5c1.png)
![image](https://cloud.githubusercontent.com/assets/2534277/20670621/a6bb113a-b5b4-11e6-91e9-fd780f4e4b6d.png)
* Connectivity is not very well, but just slow.

**Comment by benpatterson** [comment] 2016-11-28 14:14
Thanks @richard1122

**Comment by richard1122** [comment] 2016-11-28 14:21
It's an private repo inside an organization. And I'm the owner of that organization.

**Comment by richard1122** [comment] 2016-11-28 14:24
![image](https://cloud.githubusercontent.com/assets/2534277/20671701/639493b8-b5b9-11e6-912e-c8eb0e4a3c43.png)
Here are all the scopes used.

**Comment by sjstyle** [comment] 2016-11-29 15:42
Hi, I am also suffering from this issue.
I'm using Github Enterprise 2.8 with Github Pull Request Builder plugin 1.33.2
(but, this also occurs at the master branch)

In my opinion, this is more complex issue because it related to `github-api`.
This error is occurs at this point ( https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java#L365 ) 
by calling `listCommits`. 

But, github's hook returns api url `/repos/:user/:repo/issues/:pr_number` not `/repos/:user/:repo/pulls/:pr_number`.

`github-api` project's `GHPullRequest` implements are ( https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHPullRequest.java#L250 ). 
At this point, we neither could modify PR's api url nor call user defined url.

**Comment by aboivin** [comment] 2016-11-30 17:07
+1 having same issue

**Comment by benpatterson** [comment] 2016-12-01 11:21
@richard1122 if you have a cycle, could you see if this was a problem in 1.33.1? We upgraded the github-api dependency with the last release. However, grepping the commit history on the api library, nothing is sticking out to me. So, I/m trying to determine the depth of this problem.

Also, is it true that everyone on this list is using GH Enterprise? If someone is using GH public, please let me know? (I will verify on GH public when I have time, but I'm not seeing that happen for a few days at least, so thought I'd ask.)

**Comment by nMustaki** [comment] 2016-12-01 12:22
@benpatterson I am using github public on a private repo and I have this very issue. Tell me if I can do anything, I am very motivated on this one :-)

**Comment by sjstyle** [comment] 2016-12-01 12:25
@benpatterson 
I just solved this issue. In my case, it occurred when I set the label in Github PR Builder. 
I will comment more detailed source trace and pull request soon.

**Comment by benpatterson** [comment] 2016-12-01 13:02
Great news, Sang. We added label capability with this release so your
conclusion is certainly plausible.

I'll hold tight on a deeper dive, then.

**Comment by nMustaki** [comment] 2016-12-01 13:42
I have no label on my side. Currently:
- PR are built when a new commit is pushed
- PR are __not__ built when there are created or when we request a build through a comment

**Comment by sjstyle** [comment] 2016-12-01 13:59
@nMustaki 
Did you mean you leaving blank on `List of github labels for which the build should not be triggered.` to ghprb's advanced option?

**Comment by nMustaki** [comment] 2016-12-01 14:18
@sjstyle yes it's blank, not even a space, on both jenkins/configuration and myproject/configuration

**Comment by sjstyle** [comment] 2016-12-01 14:36
@nMustaki 
I think you better check `Issue Comment` in `Webhook` option on your GitHub Repository.
![image](https://cloud.githubusercontent.com/assets/4811664/20797535/84850a00-b81e-11e6-942c-89507d3d0a5a.png)
On this issue, `FileNotFoundException` occurs in Jenkins log. But I doubt your case just didn't receive any comment event on pull request.

**Comment by nMustaki** [comment] 2016-12-01 14:54
Issue comment is checked, I have the same issue as you (sadly)
```shell
Pull request #807 was updated/initialized on ORG/REPO at 12/1/16 1:21 PM by Nathan Mustaki (comment)

Dec 01, 2016 1:21:31 PM SEVERE hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException

A thread (Thread-72/1006) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.Error: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:433)
    at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:400)
    at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
    at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
    at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:365)
    at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:214)
    at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:346)
    at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:618)
    at org.jenkinsci.plugins.ghprb.GhprbRootAction$1.run(GhprbRootAction.java:233)
Caused by: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at org.kohsuke.github.Requester.handleApiError(Requester.java:592)
    at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:429)
    ... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/ORG/REPO/issues/807/commits
    at sun.reflect.GeneratedConstructorAccessor153.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at org.kohsuke.github.Requester.parse(Requester.java:524)
    at org.kohsuke.github.Requester.access$200(Requester.java:68)
    at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:424)
    ... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/ORG/REPO/issues/807/commits
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
    at org.kohsuke.github.Requester.parse(Requester.java:514)
    ... 10 more
```

**Comment by mattsch** [comment] 2016-12-01 17:35
Got the same behavior as @nMustaki, no labels anywhere but ended up with the same stack trace.  A downgrade to 1.33.1 fixed it for me.

**Comment by richard1122** [comment] 2016-12-01 17:47
Downgrade to 1.33.1 works fine for me too.
And I'm using Github Public version.

**Comment by pascalw** [comment] 2016-12-01 20:51
Just chiming in to say I'm experiencing the same issue. In my case:

* A newly created PR with a single commit was not built
* Adding a trigger comment didn't trigger a build either

**Comment by benpatterson** [comment] 2016-12-01 21:28
I will look at this once I'm free, though it might take a couple of days. We'll see if @sjstyle beats me to it, in that case.

**Comment by benpatterson** [comment] 2016-12-02 01:40
@richard1122 , et al. I believe #443 addresses this. 

Thanks for doing the initial analysis; I was able to reproduce the problem, and rolled back github-api versions. The problem appears to be introduced in 1.76 so this rolls us back to 1.75. I haven't isolated the precise change, but again this should solve the problem.

Looks like I did have some cycles to look tonight. #UnderPromiseOverDeliver

Pls let me know if you have any feedback & cheers.

**Comment by benpatterson** [comment] 2016-12-02 02:00
Ah and I should point out you may need to manually install the older github-api plugin when pulling in the fix.

**Comment by sjstyle** [comment] 2016-12-02 02:41
@benpatterson 
I solved and traced this issue by #444.

**Comment by benpatterson** [comment] 2016-12-03 01:26
I see @sjstyle 's PR and will continue reviewing that. In the meantime, I've released 1.33.3 with the downgraded github-api dependency. I was able to resolve the error described in this ticket with the downgraded github-api plugin, and via reproducing the problem, narrowed it down to the 1.76 (and beyond) release of that dependency. That said, I wasn't able to narrow down to the exact offending commit, so release 1.33.3 with only partial confidence that the problem is resolved. So, I'll look at the other PR that @sjstyle has referenced, when I have time in the coming days.

Please take the following steps if you're still seeing this error:
* Install the 1.33.3 (or greater)
* Downgrade github-api plugin manually to 1.75. You will only need to do this if you had 1.33.2 installed.
* Restart the Jenkins service and re-save your job.

I'll leave this ticket open for now; ping back if the new release has had effect. Cheers.

**Comment by AudriusButkevicius** [comment] 2016-12-04 12:22
So I've:
Updated GHPRB to 1.33.3
Downgraded Github API to 1.75
Was forced to downgrade Github Authentication Plugin to 0.24 (as it requires 1.77 otherwise)
Github plugin is still at 1.24.0 (not sure if it matters)

Yet I am still getting:

```
A thread (Thread-18/121) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.Error: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:425)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:392)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:365)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:214)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:346)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:618)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$1.run(GhprbRootAction.java:233)
Caused by: java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:553)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:421)
	... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/syncthing/syncthing/issues/3765/commits
	at sun.reflect.GeneratedConstructorAccessor89.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1725)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1723)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1721)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1292)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:492)
	at org.kohsuke.github.Requester.access$200(Requester.java:69)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:416)
	... 8 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/syncthing/syncthing/issues/3765/commits
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1674)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:486)
	... 10 more
```

Any workarounds?

**Comment by benpatterson** [comment] 2016-12-04 12:44
I'm assuming you also restarted Jenkins?

No other options at the moment. I've not had a chance to debug in depth.
I'm hoping to have time for that this week.

**Comment by AudriusButkevicius** [comment] 2016-12-04 13:01
Yeah I have restarted jenkins and resaved all thejobs.

**Comment by benpatterson** [comment] 2016-12-04 13:21
OK. Thanks for pinging back.

**Comment by sjstyle** [comment] 2016-12-04 13:28
@AudriusButkevicius 
Can you verify my solution works?
If you installed Git, JDK 7 (or above) and maven 3, you can compile and run my solution at #444 .

```
git clone https://github.com/sjstyle/ghprb-plugin.git
cd ghprb-plugin
git checkout add/whitelist-label
mvn compile package -Dmaven.test.skip=true
```

Go to jenkins plugin manager, 'Advanced' option and upload `./target/ghprb.hpi` in directory and restart jenkins.

You can roll back to previous version by jenkin's plugin manager.

**Comment by AudriusButkevicius** [comment] 2016-12-04 13:45
That has a lot of things I'd rather not pull in, if there is a branch with just the fix, let me know.

**Comment by benpatterson** [comment] 2016-12-05 03:33
I've narrowed down the problem to `checkLabels()`. Labels are only available in the [github *issues* API](https://developer.github.com/v3/pulls/#labels-assignees-and-milestones). 

In terms of implementation, as a way of obtaining labels through the Jenkins github-api repo, the pr object is being rewritten with the [fetchIssue](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHPullRequest.java#L131) call. The result is `pr.url` has `issues` in the path rather than `pulls`, as other folks on this list have observed. For now I'm going to plan on reverting the labels PR. (Looks like the @sjstyle fix will not resolve that issue since `getLabels` is called in that version of code as well.)

**Comment by sjstyle** [comment] 2016-12-05 04:01
@benpatterson 
My solution works because `checkDirtyPullRequest()` method.

This checks whether `checkLabels()` method calls. If it called, it calls github-api to get original pull request object and destroy rewritten issue object. 

So, after `checkDirtyPullRequest` it verify that pull request object's path is `/pulls/`

**Comment by benpatterson** [comment] 2016-12-05 12:31
Thanks for pointing that out, Sang. I want to keep changes discrete in
order to reduce any noise and get a working plugin out.

I'm still planning on reverting the previous PR. That way, when looking at
your changes, we won't be under pressure and can focus on the
implementation details. Don't worry, your PR will come soon.

**Comment by benpatterson** [comment] 2016-12-05 14:14
@richard1122 version 1.33.4 should solve this problem. Pls ping back in either case. Again I noticed that some data is cached (I found that the issues URL was among the items cached, and it wouldn't be cleared until a new commit arrived.) So if you still see the problem, I'd ask questions about the state of your instance, etc.

But I'm optimistic this will solve the problem.

**Comment by ilovezfs** [comment] 2016-12-06 10:42
Looks like `@BrewTestBot test this please` is still failing after the 1.33.4 upgrade.

**Comment by AudriusButkevicius** [comment] 2016-12-06 10:46
In my case the issue is fixed.

**Comment by ilovezfs** [comment] 2016-12-06 10:48
@AudriusButkevicius where is your test phrase set? In the main Jenkins settings or in the particular job's settings or both?

**Comment by AudriusButkevicius** [comment] 2016-12-06 10:52
I think its default whatever the plugin ships. I don't think it matters.

**Comment by ilovezfs** [comment] 2016-12-06 11:18
Downgrading to 1.33.1 gets it working again for us.

**Comment by benpatterson** [comment] 2016-12-06 12:34
Hi ilovezfs... Do you have a stacktrace?

**Comment by ilovezfs** [comment] 2016-12-06 13:10
@benpatterson I'm not sure it's crashing as opposed to just deciding the comment doesn't warrant triggering the build after considering it.

**Comment by benpatterson** [comment] 2016-12-06 13:36
Ok thanks @ilovezfs .

This sounds like a distinct issue from the one associated with this ticket. Could you open a new issue and share your configuration there? I'm particularly curious about the various phrases you've set globally and within the job configuration.

Based on @AudriusButkevicius's response, I'm going to close this ticket. Everyone's feedback along the way was extremely helpful as I dove into the issue.

**Closed by benpatterson** 2016-12-06 13:36 UTC
Labels: bug, high priority

**Comment by AudriusButkevicius** [comment] 2016-12-06 14:14
Thanks for the prompt fix.

**Comment by ilovezfs** [comment] 2016-12-06 14:14
@benpatterson voilà https://github.com/jenkinsci/ghprb-plugin/issues/450
