### ISSUE TITLE
publish change list on all releases

### ISSUE THREAD

**Issue by ssbarnea** [jenkinsci/ghprb-plugin#386] opened 2016-07-20 07:52 UTC
Please publish change list as part of each release. Currently the plugin points to the Jenkins wiki which states that after version x the change-lists moved to a Github page. When you click this 2nd link you reach to a page that again is missing the current changes.

Please fix this so when you click the URL from the plugin manager you would go to a page that DOES contain the change-lists, allowing you to make an informed decision.

Jenkins plugins do have the bad habit of breaking Jenkins when updated, please don't make this maintenance process even harder.

**Comment by martenson** [comment] 2016-07-25 15:59
duplicate of https://github.com/jenkinsci/ghprb-plugin/issues/360

**Comment by benpatterson** [comment] 2016-09-30 00:16
Hi - I volunteered to help out with this repo. I'll group this with 360 as @martenson pointed out and look to address this problem.

**Closed by benpatterson** 2016-09-30 00:16 UTC

**Comment by martenson** [comment] 2016-09-30 00:18
thanks @benpatterson !
