### ISSUE TITLE
Unable to parse API Response for Commit Status Update

### ISSUE THREAD

**Issue by akeithball** [jenkinsci/ghprb-plugin#580] opened 2017-10-20 17:41 UTC
Since Oct 18, we have experienced GitHub status Ids with a value greater than the size an Int allows (4295177090).  We are receiving the following HttpException.

Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/[REPO_NAME]/statuses/[sha]
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1071)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:272)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:185)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:130)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:18)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:216)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: Failed to deserialize {"url":[URL],"id":4295177090,"state":"pending","description":"Build Started","target_url":[URL],"context":[CONTEXT],"created_at":"2017-10-20T14:24:50Z","updated_at":"2017-10-20T14:24:50Z","creator":[USER-DETAILS]}
	at org.kohsuke.github.Requester.parse(Requester.java:618)
	... 13 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4295177090) out of range of int

I'm not sure if this is an issue with this plugin or a dependency.  Might be the GitHub API plugin.  It looks like the type should be changed to a long.

**Comment by rgdoliveira** [comment] 2017-10-22 14:46
Hi @akeithball 

I'm having the same issue you reported here:
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4295371837) out of range of int`

My setup is Jenkins 2.73.2 and GitHub Pull Request Builder Plugin version 1.39.0

In my case even with this error happening Github Pull Request plugin is able to build the Pull Request fine and to write the status back in Github. But yes, seems a type issue.

**Comment by morlajb** [comment] 2017-10-29 21:16
got the same error Jenkins 2.46.3
git plugin 3.60
GitHub API Plugin 1.89
GitHub plugin 1.28.0

**Comment by jshier** [comment] 2017-10-30 18:13
Also getting this error. Reported to GitHub and they responded that the `id` field is a 64-bit integer, so it needs to be parsed as one. This is a critical issue, as the plugin is broken for any project with ids above Int.max.

**Comment by joprice** [comment] 2017-10-30 18:29
Looks like the github-api has been updated to handle this and someone submitted an update to the github api plugin https://github.com/jenkinsci/github-api-plugin/pull/16.

**Comment by mntechguy** [comment] 2017-11-06 22:17
To those getting this error, update your "github-api" plugin in Jenkins.  This will solve the problem.  When the maintainer merges this: https://github.com/jenkinsci/ghprb-plugin/pull/584 It should be fixed on update / install of this plugin.

**Comment by bjoernhaeuser** [comment] 2017-11-18 21:28
This will be solveld by the next release, because #589 is merged.

**Closed by bjoernhaeuser** 2017-11-18 21:28 UTC
