### ISSUE TITLE
Comments inexplicably triggering build

### ISSUE THREAD

**Issue by krancour** [jenkinsci/ghprb-plugin#325] opened 2016-04-21 01:22 UTC
First, let me say this is a great plugin!

Currently, we're experiencing an issue where comments _not_ containing the trigger phrase are sometimes triggering a build.  Note the "sometimes."  This isn't happening frequently (relative to the number of builds we do) or predictably, but I've seen it happen, almost at random, five times today alone.

One thing I have noticed is that in our job configuration, we have not set `onlyTriggerPhrase()`.  I am worried that may play a factor somehow.

The only documentation or comments I can find pertaining to that setting seem to indicate:

```
When set, only commenting the trigger phrase in the pull request will trigger a build.
```

Does this imply that in the absence of that setting, any / all comments can or do trigger builds?  If that is the case, I'm not sure why we don't currently see _every_ comment triggering builds.

Any information you could share about the expected behavior of the `onlyTriggerPhrase()` option would be super helpful!

__Edit:__ `onlyTriggerPhrase()` probably doesn't have much to do with it.  See below for more details from my logs and my own efforts to pinpoint what, if anything, might be wrong in the code.

**Comment by krancour** [comment] 2016-04-21 01:29
Probably related to (or a dupe of) #300

**Comment by krancour** [comment] 2016-04-21 02:31
More information...

I'm currently using version 1.31.3.

Here are some logs.  This is from when the PR in question was initially opened:

```
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #166 for deis/router
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR
INFO: Checking PR #166 for job router-pr
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #166 for deis/router
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR
INFO: Checking PR #166 for job router-pr
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbRepository onPullRequestHook
WARNING: Unknown Pull Request hook action: labeled
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #166 for deis/router
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR
INFO: Checking PR #166 for job router-pr
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbRepository onPullRequestHook
WARNING: Unknown Pull Request hook action: assigned
Apr 19, 2016 4:30:12 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest <init>
INFO: Created Pull Request #166 on deis/router by krancour (kent@deis.com) updated at: 4/19/16 4:30 PM SHA: 6dabc99aba9c27e20ba9e9825700a8967cedfae6
```

This is from when a comment inexplicably prompted a build:

```
Apr 20, 2016 12:50:18 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'do we have the corresponding jenkins jobs for this yet? I feel like having that would be a prerequisite for this' for repo deis/router
Apr 20, 2016 12:50:18 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handleComment
INFO: Checking comment on PR #166 for job router-pr
Apr 20, 2016 12:50:18 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest <init>
INFO: Created Pull Request #166 on deis/router by krancour (kent@deis.com) updated at: 4/19/16 4:30 PM SHA: 6dabc99aba9c27e20ba9e9825700a8967cedfae6
Apr 20, 2016 12:50:18 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #166 was updated on deis/router at 4/20/16 12:50 PM by User:jchauncey
```

As far as I can tell, the PR was actually re-created when the comment was added.  It seems this would only happen if the PR were missing from the `Map<Integer, GhprbPullRequest> pullRequests` used internally by instances of the `GhprbRepository` class...

So, I'm speculating that either the PR was somehow _not_ added to that map when initially created _or_ something happened to that map between when the PR was opened and the comment was added.  I'm having trouble figuring out anything beyond that.

**Comment by mmitche** [comment] 2016-05-25 22:35
Are you seeing reboots of the server between cases? I fixed a bug that was causing this to happen in our instances because the previously built hash was not saved when a PR was updated.  That fix is in the latest release

**Comment by krancour** [comment] 2016-05-26 05:24
I'm afraid I don't know whether this was correlated with a Jenkins reboot.

**Comment by benpatterson** [comment] 2016-09-30 09:17
Closing this ticket as a duplicate of #300  (but leaving the reference ticket open for now; need to verify it).

**Closed by benpatterson** 2016-09-30 09:17 UTC
