### ISSUE TITLE
Could not update commit status of the Pull Request on GitHub

### ISSUE THREAD

**Issue by bavaria95** [jenkinsci/ghprb-plugin#601] opened 2017-11-27 10:31 UTC
Could not update commit status of the Pull Request on GitHub.

Hey. I am getting the following error (it's not failing a build nor having any negative consequences, despite not looking nice to have an error there) (version 1.37.0):

```
Setting status of a4e048bd6c7893cf071dcd4aa088ebc5b3545cfb to PENDING with url https://jenkins-inspire.web.cern.ch/job/multibranch-test/73/ and message: 'Build started sha1 is merged.'
Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/bavaria95/multibranch/statuses/a4e048bd6c7893cf071dcd4aa088ebc5b3545cfb
	at org.kohsuke.github.Requester.parse(Requester.java:612)
	at org.kohsuke.github.Requester._to(Requester.java:262)
	at org.kohsuke.github.Requester.to(Requester.java:224)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1000)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:272)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:185)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:130)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:18)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:226)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Caused by: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/bavaria95/multibranch/statuses/a4e048bd6c7893cf071dcd4aa088ebc5b3545cfb","id":4349256791,"state":"pending","description":"Build started sha1 is merged.","target_url":"https://jenkins-inspire.web.cern.ch/job/multibranch-test/73/","context":"default","created_at":"2017-11-27T09:43:23Z","updated_at":"2017-11-27T09:43:23Z","creator":{"login":"bavaria95","id":1766322,"avatar_url":"https://avatars1.githubusercontent.com/u/1766322?v=4","gravatar_id":"","url":"https://api.github.com/users/bavaria95","html_url":"https://github.com/bavaria95","followers_url":"https://api.github.com/users/bavaria95/followers","following_url":"https://api.github.com/users/bavaria95/following{/other_user}","gists_url":"https://api.github.com/users/bavaria95/gists{/gist_id}","starred_url":"https://api.github.com/users/bavaria95/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bavaria95/subscriptions","organizations_url":"https://api.github.com/users/bavaria95/orgs","repos_url":"https://api.github.com/users/bavaria95/repos","events_url":"https://api.github.com/users/bavaria95/events{/privacy}","received_events_url":"https://api.github.com/users/bavaria95/received_events","type":"User","site_admin":false}}
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	... 11 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4349256791) out of range of int
 at [Source: java.io.StringReader@379735; line: 1, column: 126] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
	at org.kohsuke.github.Requester.parse(Requester.java:600)
	... 11 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4349256791) out of range of int
 at [Source: java.io.StringReader@379735; line: 1, column: 126]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	... 15 more
```

**Comment by bavaria95** [comment] 2017-11-27 10:52
![image](https://user-images.githubusercontent.com/1766322/33263246-5e508e7e-d369-11e7-8acc-21b473a7e3ae.png)
![image](https://user-images.githubusercontent.com/1766322/33263257-6bafb37e-d369-11e7-92b3-0da0d9555794.png)

Couldn't find option to disable setting this up

**Comment by bavaria95** [comment] 2017-11-27 12:38
Seems that GH returns ID number which exceeds value of unsigned int, thus it fails. Any solutions to this?

**Comment by bjoernhaeuser** [comment] 2017-11-27 15:22
You need to update the github-api plugin to the latest version. This includes the bug fix of this.

**Comment by majormoses** [comment] 2017-11-27 20:32
Looks like it has not been released as I see no git tag and it shows 1.39.0 on: https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

There is a changelog entry for it:
https://github.com/jenkinsci/ghprb-plugin/blob/master/CHANGELOG.md#--1400

Can we get a release made?

**Comment by bjoernhaeuser** [comment] 2017-11-27 20:33
There will be a release shortly. But I meant that you need to update the github-api plugin: https://wiki.jenkins.io/display/JENKINS/GitHub+API+Plugin

**Comment by majormoses** [comment] 2017-11-28 01:30
Perfect I can confirm that solves it for me.

**Comment by bavaria95** [comment] 2017-11-28 09:27
Indeed seemed to help, thanks.
Should the issue be closed?

**Comment by kordianbruck** [comment] 2017-12-03 00:19
I have version 1.90 of the Github API Plugin installed but am still getting this error. Is there anything else I can do apart wait for an update of this plugin?

**Comment by abhishek-bidgely** [comment] 2017-12-15 07:13
@kordianbruck Did you have any luck with your issue?

**Comment by kordianbruck** [comment] 2017-12-15 10:18
@abhishek-bidgely not sure how, but the error disappeared. :man_shrugging:

**Comment by bjoernhaeuser** [comment] 2018-01-13 10:06
Probably due to upgrading to the lastest github-api version :)

**Closed by bjoernhaeuser** 2018-01-13 10:06 UTC

**Comment by asrivastava2017** [comment] 2018-09-19 11:50
runpipeline
