### ISSUE TITLE
Double quotes are not properly escaped when passed to ant

### ISSUE THREAD

**Issue by kip9** [jenkinsci/ghprb-plugin#364] opened 2016-06-10 11:32 UTC
When we submit a PR containing double quotes in their description, for example:

> Some commit message with "double quotes"

It results in ant build erroring out, because of invalid escaping of command line arguments. The issue lies within following fragment:

> [workspace] $ ant '-DghprbPullTitle=Some commit message with "double quotes"' -DghprbPullAuthorLoginMention=@kip9 " build-without-tests
> Buildfile: /vol/lib/jenkins/jobs/pull-request/workspace/build.xml
> 
> BUILD FAILED
> Target "quotes" does not exist in the project "XXX". 

Ant should fire target called `build-without-tests`, but due to wrong escaping it goes wild.

I've found another report of the same issue on Jenkins JIRA tracker:

https://issues.jenkins-ci.org/browse/JENKINS-29919

Note: I've removed other ant parameters passed by your plugin from the output, as they aren't important for this particular case, and contain sensitive information.

**Comment by benpatterson** [comment] 2016-09-30 09:38
Looks like a duplicate of #327

**Closed by benpatterson** 2016-09-30 09:38 UTC

**Comment by kip9** [comment] 2016-09-30 12:40
I'll double check, but I'm 90% sure it's not the case. It's not related to "displaying" things on Jenkins side, but to passing arguments to the jobs invoked. Will post if that workaround helps or not as soon as I manage to prepare test case.

**Comment by Bradeskojest** [comment] 2018-04-18 01:15
I had exactly the same problem with Jenkins and ant! When quotes are in the PR name, it tries to call ant with that.

**Comment by akhabali** [comment] 2022-03-01 14:35
We have faced a similar issue to this.

We have double quotes in the pull request description and it was causing the same issue (quotes not escaped properly) in ant command parameters.

The injected parameters were like the following:
```
[entrypoints] $ cmd.exe /C "...\ant.bat 
-file module.ant 

'"-DghprbPullLongDescription=This PR fix bug XXX \""bug description\""\r\n\r\nmore details\r\nname=xxx\r\nversion=1.0.0\r\nprovider=xxx\r\nbuildLabel=20220224-1555"'
```

The pull request description is like the following:
```
This PR fix bug XXX "bug description"

more details
name=xxx
version=1.0.0
provider=xxx
buildLabel=20220224-1555
```

plugin version 1.42.0
