### ISSUE TITLE
Comments always trigger a new build?

### ISSUE THREAD

**Issue by gionn** [jenkinsci/ghprb-plugin#300] opened 2016-03-16 09:16 UTC
Hi,

I've noticed that adding a new comment on an open PR has triggered a new build, but the comment didn't contain the configured pattern `.*test\W+this\W+please.*` (I am a new user and I am using almost default configurations for the plugin).
However, I have configured jenkins with my own API token.

Is this working as intended?

Thanks.

**Comment by DavidTanner** [comment] 2016-03-16 12:49
What settings are you using inside the job?

**Comment by gionn** [comment] 2016-03-16 13:16
I noticed that the PR that got retriggered with my comment was in failed state, while other PRs with the last commit green doesn't triggered a new build.

Screenshot of job configuration attached.

Thanks!

![screenshot from 2016-03-16 14 13 05](https://cloud.githubusercontent.com/assets/71768/13813344/574c6c8c-eb81-11e5-8e87-ef821a994758.png)
![screenshot from 2016-03-16 14 13 48](https://cloud.githubusercontent.com/assets/71768/13813343/572c0992-eb81-11e5-97f7-9ff6a4e66878.png)

**Comment by clifff** [comment] 2016-05-12 18:40
We are seeing this too, although with slightly different settings - instead of every request building automatically, it's only org members and all org members are admins.

**Comment by benpatterson** [comment] 2016-09-30 09:11
Hi - I'm helping out with this repo and looking at some of the open issues. Could this be the case because your job config (as opposed to global config) has the test phrase set as blank? Or, similarly, I don't suppose there's a space character in the field? Thanks.

**Comment by benpatterson** [comment] 2016-10-09 18:19
Unable to reproduce on latest version of plugin + Jenkins 2.7.x, even when I leave the trigger phrase blank like the example here. I'm going to close it.

**Closed by benpatterson** 2016-10-09 18:19 UTC
Labels: needs verification
