### ISSUE TITLE
PR trigger does not work with multiple git repositories

### ISSUE THREAD

**Issue by nikhil-zinjurde-imgtec** [jenkinsci/ghprb-plugin#357] opened 2016-06-02 10:20 UTC
I have a jenkins job which requires building pull requests from multiple repositories in a GitHub organisation, the source from these repositories is built together using a build script to get a final output artifact.  The SCM step offers Git to configure with multiple repositories with the same Branch Specifier, that is anyway what I want.  There is also the option of using Multiple SCMs to have Git repositories configured separately as required by this plugin.

I have tried both ways, but the PR trigger does not work.  This plugin also requires the GitHub project URL to be mentioned, since I have multiple projects in one organisation, I cannot add all the project URLs.  Also, not adding the GitHub project URL does not help in triggering the PR job.  I am having to resort to an alternate method, that is to have multiple jobs checking for pull requests for each of the repositories, and then they in turn trigger a build job.  Ideally, I would have liked to do all in one job as I am using the ghrbGitRepository and ghrpbPullId environment variables in my build script, not sure whether I will be able to pass these from the PR jobs to the build job.

Is this an intentional limitation of the plugin or is there a way of doing this that I don't know of?

**Comment by DavidTanner** [comment] 2016-06-02 11:35
This plugin is tied directly to github.  You might be able to find other plugins that offer the same functionality for other scm tools.

**Comment by nikhil-zinjurde-imgtec** [comment] 2016-06-02 11:40
Sorry that I didn't make it clear.  All my repositories/projects are on github.  The repositories/projects are part of a github organisation. I can use this plugin to trigger a pull request job for a single github repository/project, but I couldn't make the same job work with multiple github repositories/projects. Is this a limitation or am I missing something in my job configuration?

**Comment by DavidTanner** [comment] 2016-06-02 15:08
Okay.  As the plugin is programed right now it isn't modular.

**Comment by nikhil-zinjurde-imgtec** [comment] 2016-06-03 06:27
Thanks for your response to confirm the functionality offered by the plugin.  I hope this can be added as an enhancement, where the plugin can poll for multiple github projects in a single or multiple github organisations, and triggers a build for a pull request created in any of these projects.

**Comment by benpatterson** [comment] 2016-09-30 09:35
This looks like a duplicate of #261.

**Closed by benpatterson** 2016-09-30 09:35 UTC

**Comment by foiseworth** [comment] 2017-11-22 13:56
@DavidTanner @benpatterson to clarify:
- in my jenkins project I can Source Code Management, I select Git
- I then add multiple repos from the same Git instance
- I then configure the ghprb either via hooks or polling
- Pull requests then trigger the job only on the first repo.

I just want to confirm that this isn't supported and thus is expected? 😄
