### ISSUE TITLE
Consider option to cancel previous running builds when new build is triggered

### ISSUE THREAD

**Issue by mmitche** [jenkinsci/ghprb-plugin#272] opened 2016-02-19 00:54 UTC
This would be awesome.  When a new build is triggered for a job for a PR, it would be great to be able to cancel currently running versions, especially since they are now irrelevant

**Comment by philipbjorge** [comment] 2016-02-19 18:08
We're also interested in this feature.
Can anyone comment on what work they think would be involved in doing this feature?

**Comment by philipbjorge** [comment] 2016-02-19 18:09
Also, this is a dupe of #241

**Closed** 2016-02-25 23:19 UTC
