### ISSUE TITLE
Example of configuring this via Groovy

### ISSUE THREAD

**Issue by martinb3** [jenkinsci/ghprb-plugin#177] opened 2015-09-21 16:36 UTC
Hi there -- I was wondering if you had an example of configuring this plugin with Groovy? I'm trying to automate the overall "System Configuration" settings for the plugin, such as the API token and admin list. I can create a credential programmatically, but I need to figure out how to set it as the main one on the plugin.

Thanks!

**Comment by DavidTanner** [comment] 2015-09-22 03:00
@KostyaSha might have some advice, I have not really used Groovy to configure things.

**Comment by kpettijohn** [comment] 2015-10-29 06:24
@martinb3 I was able to automate the configuration using this [groovy script](https://gist.github.com/kpettijohn/e294c50e29ca4e8a329e).

**Comment by bjoernhaeuser** [comment] 2017-11-18 21:56
Closing this for now.

**Comment by lhagemann** [comment] 2018-02-06 20:52
The above referenced groovy script fails with:
`groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.jenkinsci.plugins.ghprb.GhprbGitHubAuth(java.lang.String, java.lang.String, java.lang.String, java.lang.String, null)`

The documentation around a configuration script is really valuable. Would like to see this issue reopened.

**Comment by lhagemann** [comment] 2018-02-08 17:04
This line in the `configure` method is the cause of the inability to configure this plugin completely with groovy:
`githubAuth = req.bindJSONToList(GhprbGitHubAuth.class, formData.get("githubAuth"));`

The `StaplerRequest` object, in a straight up groovy config is null, as there is no request. Following the test code is not useful, as the actual call Stapler is mocked out, so it doesn't expose this issue. 

An example of using Groovy to mock a valid StaplerRequest object for handing to the `configure()` method would be valuable. 

As it is, we will not be using the plugin, as we are unable to configure the plugin via groovy during our system configuration process.

**Comment by lhagemann** [comment] 2018-03-07 00:25
Found an example of groovy config, including how to set up the StaplerRequest object:

https://github.com/edx/jenkins-configuration/blob/master/src/main/groovy/4configureGHPRB.groovy#L83-L89

**Comment by smugcloud** [comment] 2018-06-29 21:30
For anyone else coming across this, the example @lhagemann posted helped me, but it also turned out to be a simple matter of the number of arguments I passed to `GhprbGitHubAuth`.  Here's my working config:

```
import java.lang.reflect.Field
import jenkins.model.*
import org.jenkinsci.plugins.ghprb.*

def descriptor = Jenkins.instance.getDescriptorByType(org.jenkinsci.plugins.ghprb.GhprbTrigger.DescriptorImpl.class)

Field auth = descriptor.class.getDeclaredField("githubAuth")

auth.setAccessible(true)

githubAuth = new ArrayList<GhprbGitHubAuth>()
githubAuth.add(new GhprbGitHubAuth("https://my.ghe.us/api/v3", "sha", "test1", "sha", null, null))

auth.set(descriptor, githubAuth)

descriptor.save()

return
```

**Comment by nagarakesh4** [comment] 2018-09-17 18:22
Does someone has a groovy example on retrieving existing/configured GHPRB servers with credentialID (same as UI) ?

**Closed** 2018-10-21 17:54 UTC
Labels: documentation
