### ISSUE TITLE
Context and commit status URL do not work

### ISSUE THREAD

**Issue by martin-brennan-csnet** [jenkinsci/ghprb-plugin#167] opened 2015-09-03 02:51 UTC
Hi, I have set the context and commit status URL in the Configure System section of Jenkins as shown below.

![image](https://cloud.githubusercontent.com/assets/10840857/9649570/296c61cc-523a-11e5-936c-3a1c5e3bc344.png)

However, the context that comes through in the PRs is just default and the URL is the normal job URL that is the default. Is there any reason why this might be happening, have I missed something? Thanks.

![image](https://cloud.githubusercontent.com/assets/10840857/9649590/67961fce-523a-11e5-8972-51b1cf4acbda.png)

**Comment by jlebon** [comment] 2015-09-04 15:23
Same issue here. It seems like creating a job comes with its own all blanked out Trigger Setup. If you go in the job configuration, then click "Trigger Setup...", it will show all blank fields, which will cause the defaults to take action. If you then delete that Trigger Setup and add back a new one (Trigger Setup --> Add --> "Update commit status during build"), it will have the correct field.

**Comment by jlebon** [comment] 2015-09-04 15:30
Seems like this bug has also been reported in JIRA:
https://issues.jenkins-ci.org/browse/JENKINS-29151

**Comment by DavidTanner** [comment] 2015-09-04 16:32
This is cause by this line: https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.27/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L94  I will have it fixed in the next release.

**Comment by jlebon** [comment] 2015-09-04 16:46
@DavidTanner Awesome. Do you expect a release anytime soon?

Also, related to this, it seems like there's no way currently to not have a Commit Status URL. E.g. I don't want any "Details" link at all on the PR's webpage. I can get this to work if I specify a simple space " " in that field in the Configure System page, but then when I do the steps described in my previous comment on the job configuration page to get back those defaults, the space is not copied over (trimmed out probably), and thus, the default URL gets used.

Hopefully, these two bugs are related. I.e. once we no longer have to fiddle with specific job configurations and instead rely on the main system configuration, each individual job without a Trigger Setup created will just lookup those central values without trimming anything, so that even a single blank space is kept.

**Comment by DavidTanner** [comment] 2015-09-04 16:54
How about if the url is set to ```--none--``` then the url is set to ```""```?

**Comment by jlebon** [comment] 2015-09-04 17:03
Actually, it seems like the issue is more grave than I thought. The Commit Status URL doesn't seem to be copied over at all when adding a Trigger Setup on the job configuration page. I had a assumed previously it was because I used a simple space. But even when using "--none--" now (or even a real URL), it seems like it doesn't get copied over.

**Comment by DavidTanner** [comment] 2015-09-04 17:09
There is no --none-- currently.  I am working on fixing the defaults.

**Comment by martin-brennan-csnet** [comment] 2015-09-06 05:58
So this did not work globally for me but it did work when I put the settings in there for a specific job, so my issue is solved even though there may be a larger problem at play.

**Comment by pmorie** [comment] 2015-09-09 23:04
I ran into a permutation of this today.  I am able to set these values correctly via the Web UI, but when uploading generated configuration via the Jenkins Job Builder tool (which is just posting an XML file to the API), everything under `SimpleStatus` appears to be lost.

**Comment by pmorie** [comment] 2015-09-09 23:04
Actually, I might be hitting a distinct issue

**Comment by jlebon** [comment] 2015-09-23 16:03
This issue should be fixed in the latest release.

**Comment by samrocketman** [comment] 2016-02-09 23:09
I confirm this still is an issue with ghprb 1.30.1.

**Comment by DavidTanner** [comment] 2016-02-10 00:07
@samrocketman can you post your job config and the global plugin config?

**Comment by samrocketman** [comment] 2016-02-14 03:57
To be clear: I replicated the behavior by not configuring the job config at all but instead _only_ configuring the global config.  I can't give you the config I used.

**Comment by bskrtich** [comment] 2017-02-07 01:23
This is still an issue as of ghprb-1.35.0

**Comment by benpatterson** [comment] 2017-02-07 11:03
@bskrtich is the issue similar to what's described: something you can work around if you override the default on each job?

**Comment by bskrtich** [comment] 2017-02-07 19:15
Yes the issue is very similar. If you change the Context in the global settings, it will be added to the PR at the start, but at some point durning the build it will send "default" as the Context. This all can be worked around by setting the Context in each job.

**Comment by csizmazia** [comment] 2017-02-14 13:22
Unfortunately, the described workaround (setting Context in each job) does not work for me.
To understand the problem, i did the following:
 - set "jenkins-global" as Context in the global jenkins config
 - set "jenkins-tests-only" and "jenkins-code-analysis" as Context in job-specific configurations (there are only those two jobs)

Now, all my pull requests show 4 checks: "default", "jenkins-global", "jenkins-tests-only", "jenkins-code-analysis" (see attached image)
![jenkins](https://cloud.githubusercontent.com/assets/2581924/22930523/00ca96b6-f2c1-11e6-8147-c09792f0d175.jpg)

**Comment by anton-unity** [comment] 2017-03-15 12:01
Can confirm workaround does not work for me as well

**Comment by anton-unity** [comment] 2017-03-30 08:56
@benpatterson sorry, but do you know is someone working on this?

**Comment by benpatterson** [comment] 2017-03-31 14:36
@anton-unity I am looking at it this morning and am unable to reproduce. :( 

I wonder what version of the github plugin you're using, just out of curiosity? We upgraded that dependency with 1.35.

More details: I'm setting only the context in the global configuration (not the url or anything like that, in part to simplify), and I'm setting a specific context in a ghprb job. Only the specific job's context is appearing throughout the cycle (on trigger, on start, on complete). FWIW the job is configured to pass.

**Comment by benpatterson** [comment] 2017-03-31 14:37
Oh I should also point out that my dev environment is on a jenkins 2.x install

**Comment by anton-unity** [comment] 2017-03-31 14:49
I tried it once again now with such setup - plugin v1.35 and jenkins 2.19.x.
For global configuration only context `context-global`, for job job - only context `context-job`.

That's result after job completed:
![screen shot 2017-03-31 at 17 45 04](https://cloud.githubusercontent.com/assets/15607374/24555554/454c40c2-163a-11e7-9885-a98f180fe802.png)

Job configuration:
![screen shot 2017-03-31 at 17 43 49](https://cloud.githubusercontent.com/assets/15607374/24555583/638b5c30-163a-11e7-873a-064a9d3791a0.png)

Global configuration:
![screen shot 2017-03-31 at 17 43 25](https://cloud.githubusercontent.com/assets/15607374/24555591/6b9ee644-163a-11e7-9c62-97aa70201e65.png)

**Comment by anton-unity** [comment] 2017-03-31 14:52
I will try fresh jenkins+plugin instance early next week (just to make sure there is no weird dependencies issue) and post results here.

**Comment by benpatterson** [comment] 2017-03-31 22:31
@anton-unity Ahh thank you for the screenshots. The extra pixels on the bottom of the job screenshot helped me understand how you'd configured the job. I can now happily (?) report that I can reproduce the problem. In my set-up, I was setting the job-specific configuration in the `Trigger Setup...` section of the job.

FWIW as a temporary workaround, you could try setting the job-specific context in the Trigger Setup section. (Let me know if that helps?) I'll see if I can unwind what's going on in the particular use-case where I can reproduce the problem.

![image](https://cloud.githubusercontent.com/assets/2004678/24571547/f2e37228-163f-11e7-8215-9814ddf3a373.png)
![image](https://cloud.githubusercontent.com/assets/2004678/24571602/418fc160-1640-11e7-8923-4d3b7ddfd52c.png)

**Comment by anton-unity** [comment] 2017-04-01 09:25
@benpatterson thank you for your reply! Indeed, I confirm `Job -> Trigger Setup` context work as expected and solved my problem with single job. Sorry, I was a bit confused  by few concurrent options...

This is my result with configured trigger setup (and any global configuration):
<img width="624" alt="screen shot 2017-04-01 at 12 13 11" src="https://cloud.githubusercontent.com/assets/15607374/24577393/aefc6010-16d5-11e7-880d-c89d5e4b2504.png">

**Comment by bjoernhaeuser** [comment] 2017-11-18 21:56
I am closing this, because this seems to work if properly configured. 

If anyone wants to provide a documentation patch that would be much appreciated.

**Closed by bjoernhaeuser** 2017-11-18 21:56 UTC
Labels: bug

**Comment by heisian** [comment] 2019-06-21 23:34
I think this needs to be reopened, as setting the global config context still results in `default`.
