### ISSUE TITLE
Incorrect pull request URL

### ISSUE THREAD

**Issue by rantav** [jenkinsci/ghprb-plugin#74] opened 2015-03-15 15:58 UTC
When using ghprb the HTML link to the pull request seems to be broken. 

![all-pull-request-builder__jenkins_](https://cloud.githubusercontent.com/assets/87037/6656712/c1bc898e-cb3a-11e4-91ac-1d3acfe905ee.png)

The link should be something like  `https://github.com/totango/main/pull/1206`
But in reality it's something like: `https://api.github.com/repos/totango/main/pulls/1206` (broken link)

Browsing the code, it seems that the issue stems from incorrect call to `getUrl()` here https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java#L69

I think (well, guessing) that simply changing the call to `getHtmlUrl()` might solve the issue. 
What's not clear is - how did this break and why am I the only person suffering from this?...  
Another theory is that it's a configuration option I might have missed somewhere... 

Perhaps this is something about incompatible versions of the plugins. Anyway the `GitHub Pull Request Builder` version is `1.16-8` (I tried downgrading to `1.12` but that didn't help).
And the version of `GitHub plugin` is `1.11`

Hope that's enough info to help you help me ;)
Thanks

**Comment by notsudo** [comment] 2015-03-16 20:57
I too am running into this issue in our system. Prior to the most recent round of Git related plugin upgrades things were working fine but now the pull request URLs are incorrect.
GitHub Pull Request Builder: 1.16-8
GitHub plugin: 1.11
GitHub API Plugin: 1.63

**Comment by KostyaSha** [comment] 2015-03-16 21:05
Reproduced, @notsudo could you try downgrade github-api-plugin to 1.59?

**Comment by rantav** [comment] 2015-03-16 21:19
If other folks are able to repro this, then I guess the fix is either to downgrade of to fix the code as suggested above (replace `getUrl` with `getHtmlUrl`). I'd suggest a PR but I've never developed a jenkins plugin and I don't think I'll have time to work on it in the near future.

**Comment by KostyaSha** [comment] 2015-03-16 21:23
@rantav Sorry, i'm developer and i'm asking to do some actions, of course this will be fixed

**Comment by DavidTanner** [comment] 2015-03-16 21:27
@KostyaSha I have the project open currently and can make the fix and release.

**Comment by notsudo** [comment] 2015-03-16 21:46
@KostyaSha After downgrading to github-api-plugin 1.59 it looks like new PRs have a proper URL now.

**Comment by KostyaSha** [comment] 2015-03-16 21:49
@notsudo thanks for info

**Comment by KostyaSha** [comment] 2015-03-25 19:41
@DavidTanner i think api will not be changed so feel free to do hotfix release

**Comment by DavidTanner** [comment] 2015-03-26 02:42
will do, thanks

On Wed, Mar 25, 2015 at 1:41 PM, Kanstantsin Shautsou <
notifications@github.com> wrote:

> @DavidTanner <https://github.com/DavidTanner> i think api will not be
> changed so feel free to do hotfix release
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/ghprb-plugin/issues/74#issuecomment-86187937>
> .
>



-- 
David Tanner

3 Nephi 5:13 <http://lds.org/scriptures/bofm/3-ne/5.13?lang=eng#12> Behold,
I am a disciple of Jesus Christ, the Son of God. I have been called of him
to declare his word among his people, that they might have everlasting life.

**Closed** 2015-03-26 03:46 UTC
