### ISSUE TITLE
Failures with protected branches

### ISSUE THREAD

**Issue by arcivanov** [jenkinsci/ghprb-plugin#175] opened 2015-09-15 18:46 UTC
With new protected branch features of GitHub the long-standing problem of GHPRB finally bit us in the butt: GHPRB-Merge issues a merge before issuing a success for status check update.

With protected branches you get this:

```
2015-09-15 18:33:39.928: Merging the pull request
2015-09-15 18:33:40.006: ERROR: Publisher 'Github Pull Request Merger' aborted due to exception: 
2015-09-15 18:33:40.007: java.io.IOException: {"message":"Required status check \"default\" is pending","documentation_url":"https://help.github.com/articles/about-protected-branches"}
```

Solution is simple - report status first then merge if you can/want to.

**Comment by DavidTanner** [comment] 2015-09-21 20:10
The problem is that the merge step is a post-build step, and the status update only happens after all post build steps complete.

**Comment by DavidTanner** [comment] 2015-09-21 20:11
The merge would need to be made as part of the trigger and run after the build finishes instead of as a post-build step.

**Comment by arcivanov** [comment] 2015-09-21 20:12
Yep. Btw, can you add me to maintainers so that I don't have to bother you every time?

**Comment by DavidTanner** [comment] 2015-09-22 19:48
So I have two ideas, one is that the merge logic gets added as an extension that is configured inside the trigger setup, then it can be run after the status is updated.  And second the merge post build step could be enhanced to set the status of the commit with the status before it attempts the merge.

**Comment by arcivanov** [comment] 2015-09-22 20:03
What about adding merge as a post-build step as with status update? You still can fail the build if the merge fails for whatever reason.

**Comment by arcivanov** [comment] 2015-09-22 20:05
I just don't see the two working as separate pieces of functionality, frankly, now that GH introduced the protected branches. Even before the branch protected "merge happened while tests were pending" was logged.

**Comment by DavidTanner** [comment] 2015-09-22 20:13
I am not opposed to removing the post-build step, and making it a part of the trigger build complete steps.  As long as it doesn't break other functionality that depends on the merge happening before other steps complete.

**Comment by arcivanov** [comment] 2015-09-22 20:14
K, let me try to prototype something tonight.

**Comment by ppadial** [comment] 2015-10-02 08:21
hi all,

theres any update on this?

**Comment by arcivanov** [comment] 2015-10-02 08:34
I'll be working on this soon, it's in my queue.

**Comment by ppadial** [comment] 2015-10-02 08:38
great!! thank you for ur work !!

**Comment by ngbinh** [comment] 2015-10-29 17:22
Any update? Thanks

**Comment by kratsg** [comment] 2016-08-11 11:31
I'm running into this issue (http://build.ci-connect.net:8080/job/RootCore/job/xAH/580/console)

**Comment by ijunes** [comment] 2016-11-23 19:13
+1 the status check that mine refers to is set by a downstream job manually. the status check shows passed on github but the api response from the plugin appears to be mismatched.

**Comment by bjoernhaeuser** [comment] 2017-11-18 20:21
Is this issue still happening? :)

**Comment by bjoernhaeuser** [comment] 2017-11-18 21:57
Closing this for now. If it still happens, please reopen.

**Closed by bjoernhaeuser** 2017-11-18 21:57 UTC
Labels: enhancement
